### ISSUE TITLE
Have this error in xcode 9 in the SwiftOverlays.swift

### ISSUE THREAD

**Issue by powervette** [peterprokop/SwiftOverlays#39] opened 2017-10-05 14:08 UTC
Incorrect argument label in call(have 'withAttributes:', expected 'attributes:')

line 477 private class methods, labelForText

**Comment by peterprokop** [comment] 2017-10-08 11:50
@powervette thanks for reporting, will take a look

**Comment by andrealufino** [comment] 2017-10-10 10:18
+1 for this, I'm having this problem also

**Comment by maysamsh** [comment] 2017-10-14 15:47
I have the same problem

**Comment by peterprokop** [comment] 2017-10-15 08:21
@powervette @andrealufino @maysamsh I'm sorry for the delay, this should be fixed now.

**Comment by maysamsh** [comment] 2017-10-15 08:52
Now it's a new error:
```
The following build commands failed:
	CompileSwift normal arm64 /Users/maysam/Developer/iOS/GreatTweets/Carthage/Checkouts/SwiftOverlays/SwiftOverlays/SwiftOverlays.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
```

**Comment by peterprokop** [comment] 2017-10-15 09:29
@maysamsh can you please try again with `github "peterprokop/SwiftOverlays" ~> 4.0.1` in Cartfile?

**Comment by maysamsh** [comment] 2017-10-15 09:48
The error is gone, thanks.

**Comment by powervette** [comment] 2017-10-15 14:13
Is this not updated in Cocoapods yet? Not sure how to update it manually.

**Comment by peterprokop** [comment] 2017-10-15 17:19
@powervette sorry, just pushed 4.0.1 to pods. Can you please try?
Also: use carthage =)

**Comment by powervette** [comment] 2017-10-15 17:46
cocoa pods  says 4.0.1 installed, but still getting the same error.

**Comment by peterprokop** [comment] 2017-10-15 17:59
@powervette I've just tried - works for me without any problems. Have you removed copied `SwiftOverlays.swift`? Can you also please try cleaning everything?

**Comment by powervette** [comment] 2017-10-15 18:03
i uninstalled it, then reinstalled it, cleaned and still get the error. Not sure what is up, maybe I will look into carthage.

**Comment by DSalehi** [comment] 2017-10-16 03:54
+1 still getting this error using cocoapods with 4.0.1

**Comment by peterprokop** [comment] 2017-10-16 13:30
@DSalehi what version of Xcode/cocoapods do you use?

**Comment by DSalehi** [comment] 2017-10-16 17:49
@peterprokop Xcode 9 with Cocoapods v1.3.1

**Comment by outdoorsole** [comment] 2017-11-28 13:34
Hello -- did this error happen to be updated for CocoaPods?

**Comment by peterprokop** [comment] 2018-10-22 09:39
The issue is fixed

**Closed by peterprokop** 2018-10-22 09:39 UTC
